// ─── HeadCheck Shared Data ────────────────────────────────────────────────────
// Single source of truth for proverbs, EI pillars, and brain-emotion mapping
// Used across LearnEI, ZeraCards, Mindset, About, AI engine

export const EI_PILLARS = [
  {
    id: "self-awareness",
    name: "Self-Awareness",
    emoji: "🪞",
    color: "oklch(0.72 0.18 285)",
    description: "Understanding your own emotions, strengths, weaknesses, and how they affect others.",
    practices: ["Daily journaling", "Mindful observation", "Emotional labeling", "Feedback reflection"],
    proverb: { text: "Know yourself and you will win all battles.", country: "African Proverb", theme: "Wisdom, alignment" },
  },
  {
    id: "self-regulation",
    name: "Self-Regulation",
    emoji: "🌊",
    color: "oklch(0.65 0.18 220)",
    description: "Managing your emotions and impulses, adapting to changing circumstances with grace.",
    practices: ["Pause before reacting", "Deep breathing", "Identify triggers", "Choose responses"],
    proverb: { text: "No matter how long the night, the day is sure to come.", country: "Ghana", theme: "Patience, endurance" },
  },
  {
    id: "motivation",
    name: "Motivation",
    emoji: "🔥",
    color: "oklch(0.72 0.18 48)",
    description: "Harnessing emotions to pursue goals with energy and persistence.",
    practices: ["Set meaningful goals", "Celebrate small wins", "Connect to purpose", "Build momentum"],
    proverb: { text: "However far a stream flows, it never forgets its source.", country: "Liberia", theme: "Purpose, perseverance" },
  },
  {
    id: "empathy",
    name: "Empathy",
    emoji: "💜",
    color: "oklch(0.65 0.18 320)",
    description: "Recognizing and understanding the emotions of others, building genuine connection.",
    practices: ["Active listening", "Perspective-taking", "Validate feelings", "Suspend judgment"],
    proverb: { text: "We are because we are.", country: "Ubuntu Philosophy", theme: "Compassion, community" },
  },
  {
    id: "social-skills",
    name: "Social Skills",
    emoji: "🤝",
    color: "oklch(0.65 0.18 160)",
    description: "Managing relationships and building networks through clear communication and collaboration.",
    practices: ["Clear communication", "Conflict resolution", "Team building", "Inspire others"],
    proverb: { text: "If you want to go fast, go alone. If you want to go far, go together.", country: "African Proverb", theme: "Communication, unity" },
  },
];

export const AFRICAN_PROVERBS = [
  // Self-Awareness
  { text: "Know yourself and you will win all battles.", country: "African Proverb", pillar: "self-awareness", theme: "Wisdom" },
  { text: "When there is no enemy within, the enemies outside cannot hurt you.", country: "African Proverb", pillar: "self-awareness", theme: "Inner strength" },
  { text: "Clarity comes with stillness.", country: "African Proverb", pillar: "self-awareness", theme: "Reflection" },
  { text: "Return to yourself.", country: "African Proverb", pillar: "self-awareness", theme: "Reconnection" },
  // Self-Regulation
  { text: "No matter how long the night, the day is sure to come.", country: "Ghana", pillar: "self-regulation", theme: "Patience, endurance" },
  { text: "Wisdom in silence and speech.", country: "African Proverb", pillar: "self-regulation", theme: "Restraint" },
  { text: "Do not fear tomorrow.", country: "African Proverb", pillar: "self-regulation", theme: "Trust, calm" },
  { text: "Healing takes time.", country: "African Proverb", pillar: "self-regulation", theme: "Healing, acceptance" },
  // Motivation
  { text: "However far a stream flows, it never forgets its source.", country: "Liberia", pillar: "motivation", theme: "Purpose, perseverance" },
  { text: "Step by step forward.", country: "African Proverb", pillar: "motivation", theme: "Purpose" },
  { text: "Rise again.", country: "African Proverb", pillar: "motivation", theme: "Hope, resilience" },
  { text: "Walk your path.", country: "African Proverb", pillar: "motivation", theme: "Vision, courage" },
  // Empathy
  { text: "We are because we are.", country: "Ubuntu Philosophy", pillar: "empathy", theme: "Compassion, community" },
  { text: "The ruin of a nation begins in the homes of its people.", country: "Ghana", pillar: "empathy", theme: "Community, responsibility" },
  { text: "A child who is not embraced by the village will burn it down to feel its warmth.", country: "African Proverb", pillar: "empathy", theme: "Belonging, care" },
  // Social Skills
  { text: "If you want to go fast, go alone. If you want to go far, go together.", country: "African Proverb", pillar: "social-skills", theme: "Unity, collaboration" },
  { text: "Words build or break.", country: "African Proverb", pillar: "social-skills", theme: "Communication" },
  { text: "Until the lion learns to write, every story will glorify the hunter.", country: "African Proverb", pillar: "social-skills", theme: "Voice, advocacy" },
];

export const BRAIN_EMOTION_MAP: Record<string, {
  brain: string;
  meaning: string;
  eiPillar: string;
  aieiTheme: string;
  exampleProverb: string;
}> = {
  overwhelmed: {
    brain: "Amygdala activated, Prefrontal cortex reduced",
    meaning: "Brain in threat mode, thinking reduced",
    eiPillar: "Self-Regulation",
    aieiTheme: "Patience, endurance",
    exampleProverb: "No matter how long the night, the day is sure to come.",
  },
  angry: {
    brain: "Amygdala highly activated, Prefrontal cortex reduced",
    meaning: "Fast emotional reaction, low impulse control",
    eiPillar: "Self-Regulation and Empathy",
    aieiTheme: "Restraint, understanding",
    exampleProverb: "Wisdom in silence and speech.",
  },
  anxious: {
    brain: "Amygdala and Hippocampus activated",
    meaning: "Fear and memory patterns triggered",
    eiPillar: "Self-Regulation",
    aieiTheme: "Trust, calm, faith",
    exampleProverb: "Do not fear tomorrow.",
  },
  sad: {
    brain: "Amygdala moderate, Hippocampus active",
    meaning: "Processing loss or emotional pain",
    eiPillar: "Self-Awareness",
    aieiTheme: "Healing, acceptance",
    exampleProverb: "Healing takes time.",
  },
  numb: {
    brain: "Low emotional activation, protective shutdown",
    meaning: "Brain protecting from emotional overload",
    eiPillar: "Self-Awareness",
    aieiTheme: "Reconnection, presence",
    exampleProverb: "Return to yourself.",
  },
  confused: {
    brain: "Prefrontal cortex overloaded",
    meaning: "Too much information, low clarity",
    eiPillar: "Self-Awareness",
    aieiTheme: "Wisdom, reflection",
    exampleProverb: "Clarity comes with stillness.",
  },
  stuck: {
    brain: "Low motivation circuits, Prefrontal reduced",
    meaning: "Low drive, unclear direction",
    eiPillar: "Motivation",
    aieiTheme: "Purpose, perseverance",
    exampleProverb: "Step by step forward.",
  },
  discouraged: {
    brain: "Low dopamine, negative loops",
    meaning: "Loss of belief or momentum",
    eiPillar: "Motivation",
    aieiTheme: "Hope, resilience",
    exampleProverb: "Rise again.",
  },
  hurt: {
    brain: "Amygdala and social pain circuits activated",
    meaning: "Emotional pain tied to relationships",
    eiPillar: "Empathy",
    aieiTheme: "Compassion, community",
    exampleProverb: "We are because we are.",
  },
  conflict: {
    brain: "Amygdala and Prefrontal imbalance",
    meaning: "Emotional and logical tension",
    eiPillar: "Social Skills",
    aieiTheme: "Communication, unity",
    exampleProverb: "Words build or break.",
  },
  reflective: {
    brain: "Prefrontal cortex active and balanced",
    meaning: "Calm thinking and insight available",
    eiPillar: "Self-Awareness",
    aieiTheme: "Wisdom, alignment",
    exampleProverb: "Know yourself.",
  },
  hopeful: {
    brain: "Balanced but unstable circuits",
    meaning: "Growth state needing direction",
    eiPillar: "Motivation",
    aieiTheme: "Vision, courage",
    exampleProverb: "Walk your path.",
  },
  stressed: {
    brain: "Amygdala activated, cortisol elevated",
    meaning: "Stress response, reduced cognitive capacity",
    eiPillar: "Self-Regulation",
    aieiTheme: "Endurance, release",
    exampleProverb: "No matter how long the night, the day is sure to come.",
  },
  frustrated: {
    brain: "Amygdala activated, reward circuits blocked",
    meaning: "Goal blocked, emotional pressure building",
    eiPillar: "Self-Regulation",
    aieiTheme: "Patience, persistence",
    exampleProverb: "Step by step forward.",
  },
};

// ─── Seven Mirrors Data ───────────────────────────────────────────────────────
export const SEVEN_MIRRORS = [
  {
    id: 1,
    theme: "Values",
    label: "Mirror 1 of 7",
    question: "What do I value most in my relationship with myself?",
    guidance: "Pause and reflect first. This establishes internal honesty.",
    journalPlaceholder: "Write freely here...",
    options: [
      "Honesty with myself",
      "Self-respect and boundaries",
      "Growth and learning",
      "Inner peace",
      "Trusting my own voice",
      "Compassion toward myself",
      "Protecting my energy",
      "Emotional safety",
      "Freedom to be authentic",
    ],
    hasOther: true,
    otherPrompt: "What else do you value?",
  },
  {
    id: 2,
    theme: "Loyalty",
    label: "Mirror 2 of 7",
    question: "What does loyalty to me look like?",
    guidance: "Reflect on how you show up for yourself, especially under pressure.",
    journalPlaceholder: "Write freely here...",
    options: [
      "Keeping promises to myself",
      "Protecting my energy",
      "Choosing my wellbeing",
      "Speaking up for my needs",
      "Resting when needed",
      "Walking away from harm",
      "Trusting my instincts",
      "Choosing myself without guilt",
    ],
    hasOther: true,
    otherPrompt: "What else does loyalty to yourself look like?",
  },
  {
    id: 3,
    theme: "Inner Conflict",
    label: "Mirror 3 of 7",
    question: "How do I handle conflict within myself?",
    guidance: "Name your patterns without judgment.",
    journalPlaceholder: "Write freely here...",
    options: [
      "I avoid and suppress emotions",
      "I overanalyze and self-criticize",
      "I become overwhelmed",
      "I numb or disconnect",
      "I push through without pausing",
      "I reflect and learn",
      "I seek support",
      "I journal or process deeply",
    ],
    hasOther: true,
    otherPrompt: "What else happens during inner conflict?",
  },
  {
    id: 4,
    theme: "Self-Appreciation",
    label: "Mirror 4 of 7",
    question: "What makes me feel appreciated by myself?",
    guidance: "Identify what nourishes your sense of worth.",
    journalPlaceholder: "Write freely here...",
    options: [
      "Rest without guilt",
      "Celebrating progress",
      "Keeping commitments",
      "Speaking kindly to myself",
      "Protecting my boundaries",
      "Listening to my body",
      "Moving at my own pace",
      "Giving myself grace",
    ],
    hasOther: true,
    otherPrompt: "What else helps you feel appreciated by yourself?",
  },
  {
    id: 5,
    theme: "Red Flags",
    label: "Mirror 5 of 7",
    question: "What red flags do I ignore within myself?",
    guidance: "Be honest about what you overlook.",
    journalPlaceholder: "What signs do you ignore?",
    options: [
      "Burnout and exhaustion",
      "Harsh inner dialogue",
      "Avoidance and procrastination",
      "People pleasing",
      "Ignoring my needs",
      "Overcommitting",
      "Dismissing intuition",
      "Acting like I am fine",
    ],
    hasOther: true,
    otherPrompt: "What other red flags do you notice?",
  },
  {
    id: 6,
    theme: "Growth",
    label: "Mirror 6 of 7",
    question: "What am I currently working on within myself?",
    guidance: "Locate growth without shame.",
    journalPlaceholder: "Write freely here...",
    options: [
      "Emotional regulation",
      "Confidence and self-trust",
      "Boundaries",
      "Healing past experiences",
      "Self-compassion",
      "Consistency",
      "Letting go of perfectionism",
      "Being present",
    ],
    hasOther: true,
    otherPrompt: "What else are you working on?",
  },
  {
    id: 7,
    theme: "Peace",
    label: "Mirror 7 of 7",
    question: "What does peace with me look like?",
    guidance: "Envision internal alignment and calm.",
    journalPlaceholder: "Write freely here...",
    options: [
      "Calm in my body",
      "Trusting my choices",
      "Releasing perfection",
      "Speaking kindly to myself",
      "Moving at my natural pace",
      "Inner quiet without guilt",
      "Balanced rest and action",
      "Feeling emotionally safe",
    ],
    hasOther: true,
    otherPrompt: "What else does peace with yourself look like?",
  },
];

export const REFLECTION_BADGES = [
  { id: "self-trust", label: "Self Trust", emoji: "🌟", color: "oklch(0.72 0.18 285)" },
  { id: "growth", label: "Growth", emoji: "🌱", color: "oklch(0.65 0.18 160)" },
  { id: "healing", label: "Healing", emoji: "💜", color: "oklch(0.65 0.18 320)" },
  { id: "boundaries", label: "Boundaries", emoji: "🛡️", color: "oklch(0.65 0.18 220)" },
  { id: "inner-peace", label: "Inner Peace", emoji: "☮️", color: "oklch(0.72 0.18 48)" },
  { id: "emotional-safety", label: "Emotional Safety", emoji: "🏡", color: "oklch(0.65 0.18 140)" },
];

// ─── Check-In Steps Data ──────────────────────────────────────────────────────
export const CHECKIN_STEPS = [
  {
    step: 1,
    type: "single" as const,
    question: "What feels strongest for you right now?",
    helper: "There is no right or wrong answer. Start with what feels most true.",
    options: ["Overwhelmed", "Anxious", "Stressed", "Sad", "Angry", "Discouraged", "Numb", "Confused", "Frustrated", "Hopeful but uncertain"],
    hasOther: true,
    otherPrompt: "Tell us more",
    saveKey: "emotion",
  },
  {
    step: 2,
    type: "multi" as const,
    question: "What might be contributing to how you feel right now?",
    instruction: "Select all that apply",
    options: ["Assignment deadline", "Exam or quiz", "Understanding course material", "Communication with instructor", "Group project stress", "Time management", "Work-life balance", "Family responsibilities", "Financial pressure", "Feeling behind", "Lack of motivation", "Not feeling supported", "Not sure"],
    hasOther: true,
    otherPrompt: "What else is affecting you right now?",
  },
  {
    step: 3,
    type: "multi" as const,
    question: "How is this affecting you emotionally?",
    instruction: "Select all that apply",
    options: ["I feel pressured", "I feel afraid of falling behind", "I feel disappointed in myself", "I feel ashamed", "I feel mentally exhausted", "I feel scattered", "I feel discouraged", "I feel alone in this", "I feel frustrated", "I feel unsure what to do next", "I feel hopeful but uncertain"],
    hasOther: true,
    otherPrompt: "What else are you feeling?",
  },
  {
    step: 4,
    type: "multi" as const,
    question: "Which feelings feel most intense right now?",
    instruction: "Select all that apply",
    helper: "Naming your feelings can help reduce their power.",
    options: ["Fear", "Pressure", "Disappointment", "Shame", "Confusion", "Frustration", "Hopelessness", "Isolation", "Stress", "Emotional overload"],
    hasOther: true,
    otherPrompt: "What feeling would you add?",
  },
  {
    step: 5,
    type: "multi" as const,
    question: "Which of these might also be affecting you right now?",
    instruction: "Select all that apply",
    options: ["Lack of sleep", "Hunger or low energy", "Mental overload", "Financial challenges", "Family stress", "Too many responsibilities", "Not enough time", "Lack of structure", "Feeling unsupported", "Burnout"],
    hasOther: true,
    otherPrompt: "What else may be affecting you?",
  },
  {
    step: 6,
    type: "single" as const,
    question: "What feels most supportive for you right now?",
    guidance: "Sometimes support begins with clarity. Sometimes it begins with rest. Sometimes it begins with reaching out.",
    options: ["A clearer understanding of what I am feeling", "Help calming down", "Encouragement and perspective", "A small next step", "Someone to talk to", "Time to pause and breathe", "Help organizing what matters first"],
    hasOther: true,
    otherPrompt: "What would feel supportive right now?",
  },
  {
    step: 7,
    type: "single" as const,
    question: "What feels possible for you right now?",
    helper: "Choose what feels realistic, not perfect.",
    options: ["Send one email", "Start one small task", "Write down questions", "Ask for help", "Take a short break", "Make a simple plan", "Pause and come back later", "Do one thing at a time"],
    hasOther: true,
    otherPrompt: "What feels possible for you right now?",
  },
  {
    step: 8,
    type: "single" as const,
    question: "Who or what kind of support could help you succeed?",
    reflection: "Using this tool is a strong first step. Reaching out for support can be the next one.",
    options: ["Instructor", "Academic advisor", "Tutor", "Classmate or study group", "Financial aid or support services", "Mental health or counseling support", "Friend or family member", "Not sure yet", "Not ready yet"],
    hasOther: true,
    otherPrompt: "Who or what support would you add?",
  },
  {
    step: 9,
    type: "single" as const,
    question: "Did this check-in help?",
    options: ["Yes, I feel clearer", "Somewhat, I feel calmer", "Not yet"],
    conditionalMessage: "That is okay. Sometimes clarity takes more than one moment. We can still help you identify a next step.",
  },
  {
    step: 10,
    type: "single" as const,
    question: "Would you like to save this check-in for yourself?",
    whyItWorks: "This check-in helps you pause instead of panicking, name instead of suppressing, and move forward instead of shutting down.",
    whyItWorksTitle: "Why This Works",
    options: ["Yes", "No"],
  },
];
